apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ramilano/helm-demo-app.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: product
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
       - CreateNamespace=false
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
